[package]
name = "rust_sandbox"
version = "0.1.0"
authors = ["Jingjing Duan <duanjingjing@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
float-cmp = "0.6"
futures = "0.3"
rand = "0.7.2"
regex = "1"
serde = {version = "1.0", features = ["derive"]}
serde-xml-rs = "0.3"

[dev-dependencies]
float-cmp = "0.6"
tempfile = "3.1"
