[workspace]
members = [
    "actix_example",
    "actix_web_example",
    "rust_cli",
    "rust_green_threads",
    "rust_minigrep",
    "rust_mio_example",
    "rust_parser_combinators",
    "rust_sandbox",
    "rust_thrift_example",
    "rust_tokio_example",
    "rust_webserver",
]
